#!/usr/bin/env node
// Render the Homebrew formula for a release from its packaged .sha256 files (RUST-13).
//
//   node scripts/release/homebrew-formula.mjs --version 0.7.0 --dist dist \
//     --repo dmarzzz/shade-tree-node [--out dist/shadenet.rb]
//
// The formula installs the self-contained `-live` binary for the platform as `shadenet`,
// with `shade-tree` as an alias. Targets with no packaged live asset are left out.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";

const { values: a } = parseArgs({
  options: {
    version: { type: "string" },
    dist: { type: "string", default: "dist" },
    repo: { type: "string" },
    out: { type: "string" },
  },
});
if (!a.version || !a.repo) throw new Error("usage: --version <x.y.z> --repo <owner/name> [--dist dir] [--out file]");
if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(a.version)) throw new Error(`bad version ${a.version}`);
if (!/^[\w.-]+\/[\w.-]+$/.test(a.repo)) throw new Error(`bad repo ${a.repo}`);

// Homebrew platform block -> release target. musl builds are static, so they run on any
// Linux Homebrew supports.
const PLATFORMS = [
  ["macos", "arm", "aarch64-apple-darwin"],
  ["macos", "intel", "x86_64-apple-darwin"],
  ["linux", "arm", "aarch64-unknown-linux-musl"],
  ["linux", "intel", "x86_64-unknown-linux-musl"],
];

function asset(target) {
  const name = `shadenet-${a.version}-${target}-live`;
  const shaFile = join(a.dist, `${name}.sha256`);
  if (!existsSync(shaFile)) return null;
  const [hex, file] = readFileSync(shaFile, "utf8").trim().split(/\s+/);
  if (!/^[0-9a-f]{64}$/.test(hex) || file !== name) throw new Error(`malformed ${shaFile}`);
  return { name, hex };
}

const blocks = { macos: [], linux: [] };
for (const [os, cpu, target] of PLATFORMS) {
  const found = asset(target);
  if (!found) continue;
  blocks[os].push(
    `    on_${cpu} do\n` +
      `      url "https://github.com/${a.repo}/releases/download/v${a.version}/${found.name}"\n` +
      `      sha256 "${found.hex}"\n` +
      `    end`,
  );
}
if (!blocks.macos.length && !blocks.linux.length) throw new Error(`no live assets for ${a.version} in ${a.dist}`);

const osBlock = (os) => (blocks[os].length ? `  on_${os} do\n${blocks[os].join("\n")}\n  end\n` : "");

const formula = `# Generated by scripts/release/homebrew-formula.mjs for v${a.version}. Do not edit by hand.
class Shadenet < Formula
  desc "Proof-gated Tor egress for agents (ShadeNet research preview)"
  homepage "https://github.com/${a.repo}"
  version "${a.version}"
  license "MIT"

${osBlock("macos")}${osBlock("linux")}
  def install
    bin.install Dir["shadenet-*"].first => "shadenet"
    bin.install_symlink "shadenet" => "shade-tree"
  end

  test do
    assert_match "proxy", shell_output("#{bin}/shadenet --help")
  end
end
`;

const out = a.out ?? join(a.dist, "shadenet.rb");
writeFileSync(out, formula);
console.log(`wrote ${out} (${blocks.macos.length + blocks.linux.length} platforms)`);
